name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y \
             pkg-config libpng-dev libjpeg-dev
    - name: make
      run: make
  MacOS:
    name: MacOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: make
      run: make
